name: Publish to PyPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  test:
    name: Test on ${{ matrix.os }} Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CMake
        uses: lukka/get-cmake@v3.25.1

      - name: Install Ninja
        if: runner.os == 'Windows'
        run: |
          choco install ninja
          echo "C:\Program Files\ninja" >> $GITHUB_PATH

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.0
      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install project
        run: poetry install --no-interaction

      - name: Build and install C extensions
        run: |
          cd stampix/auspostgen/_c

          # Create and configure build directory
          mkdir -p build
          cd build

          # Configure CMake
          cmake .. -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=$(which python)

          # Build
          cmake --build . --config Release

          # Install the built extension
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp Release/auspost.pyd ../
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            # Try different possible output names
            if [ -f "libauspost.dylib" ]; then
              cp libauspost.dylib ../auspost.so
            elif [ -f "auspost.dylib" ]; then
              cp auspost.dylib ../auspost.so
            elif [ -f "auspost.so" ]; then
              cp auspost.so ../auspost.so
            else
              echo "Error: Could not find the built library file"
              ls -la
              exit 1
            fi
          else
            # Try different possible output names
            if [ -f "libauspost.so" ]; then
              cp libauspost.so ../auspost.so
            elif [ -f "auspost.so" ]; then
              cp auspost.so ../auspost.so
            else
              echo "Error: Could not find the built library file"
              ls -la
              exit 1
            fi
          fi

          cd ../../../../

      - name: Run tests
        run: poetry run pytest

      - name: Run linting
        run: |
          poetry run black --check .
          poetry run isort --check .
          poetry run ruff check .

      - name: Run type checking
        run: poetry run mypy .

  semantic-release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.0
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Semantic Release Version
        id: release
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          poetry run semantic-release version --commit --vcs-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release Publish
        id: publish
        run: poetry run semantic-release publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: semantic-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, manylinux]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ENVIRONMENT_MACOS: "MACOSX_DEPLOYMENT_TARGET=11.0"
          CIBW_BEFORE_BUILD_MACOS: "pip install delocate"
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-wheel --require-archs arm64 -w {dest_dir} -v {wheel}"
          CIBW_ENVIRONMENT_MANYLINUX: "AUDITWHEEL_PLAT=manylinux_2_28_x86_64"
          CIBW_BEFORE_BUILD_MANYLINUX: "pip install auditwheel"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: wheels
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
          packages-dir: wheels
